In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re  # ← Ajouter cette ligne au début

In [46]:
df=pd.read_csv("data/doctors_export.csv")

In [47]:
df.head(30)

,id,first_name,last_name,specialty,city,location,avg_rating,rating_count,description,image
0,0b574b8d-e954-4a77-b97e-ad85b9ab5f30,Jihen,HICHERI,Dermatologue,Ariana,"Centre Médical IRIS, 2037 Av. Hédi Nouira, Ari...",4.3,47,Dermatologie - Maladies Sexuellement Transmiss...,NaN
1,a4716f9d-3d3e-41ca-8aec-a415ff92f2f9,Manel,Karray Zahaf,Dermatologue,Tunis,"Centre El Manar Médical, 2 Rue Tahar Sfar, Tun...",4.9,40,NaN,NaN
2,b8593226-d642-432b-9f02-9cae9c1697b9,Alya,GARGOURI GHARBI,Dermatologue,Tunis,"IBN NAFIS MEDICAL, 84 bis Av. Habib Bourguiba,...",4.2,45,NaN,NaN
3,550e8400-e29b-41d4-a716-446655440000,Wafa,jouini,Dermatologue,Ariana,"1er étage, Apt B1, Centre médical el andalous,...",4.7,55,Le Dr Wafa JOUINI est Dermatologue exerçant à ...,NaN
4,b89b8e98-264d-4bbe-af0a-12bedf2415e4,Jihed,Yacoubi,Dermatologue,Tunis,"Campus Médical, 1 Rue de Tolède, Tunis 2092, T...",5.0,87,NaN,NaN
5,a7f00890-2eaa-461a-ab6b-6f88c512f557,Amel,JELLOULI ELLOUMI,Dermatologue,Tunis,"5ème étage Cabinet 1, Clinique Les Jasmins, Ce...",5.0,13,Spécialiste en Dermatologie - Ancien Médecin P...,NaN
6,9f8fa7f5-e506-4704-9e17-55caeddf88b2,Yosra,JMOUR,Dermatologue,Tunis,"centre médical Lake Tower, Avenue Beji caid Es...",4.1,33,Dermatologie - Maladies de la peau - Maladies ...,NaN
7,9047dd0d-d2e2-4136-ad16-4e94cfb94d5d,Slim,BEN ALI,Dermatologue,Tunis,"Tunis, Tunisie",4.7,51,Diplôme de médecin spécialiste en dermatologie...,NaN
8,91fbabfd-f183-4f06-8e77-94d96411ed9d,Hanen,HAJ TAIEB MEHDI,Dermatologue,Tunis,Soukra Médical Cabinet N°C5 3éme étage، Rue Ch...,4.2,15,Spécialiste en Dermatologie - Maladies Sexuell...,NaN
9,d19839a8-97c2-41a1-a55a-a4408520043e,Zineb,BENNANI,Dermatologue,Tunis,"centre médical sabri, 19, bis Av. de la Républ...",4.0,45,Dermatologie - Maladies des ongles et du cuir ...,NaN
10,4d15d3ef-18c5-473d-a20a-e9e30a44380e,Rim,Cheikh Rouhou Triki,Dermatologue,Tunis,"El Bader Médical, 53 Avenue Moheiddine Klibi, ...",4.8,53,NaN,NaN
11,89b7194b-2d00-4ffe-b83e-b83bf6ccd5e7,Oumayma,Magdoud Dermatologue,Dermatologue,Tunis,"1er étage, app 6, Bloc B, Immeuble Le Palace, ...",4.8,49,NaN,NaN
12,54ef5be6-4146-4250-b9ce-eabb8185604e,Houda,Kennou dermatologue,Dermatologue,Tunis,"44 Av. de La Liberté, Tunis 1002, Tunisie",4.7,38,NaN,NaN
13,8a688677-4a3b-4305-87b0-d3c237809351,Amel,SOUISSI HAJAIEJ,Dermatologue,Tunis,"d'Amérique, 13 bis Av. Des Etats Unis, Tunis 1...",4.6,190,NaN,NaN
14,78186a02-fefa-464c-add9-e19e3341b14e,Leila,Ben Rejeb Ep Riahi,Dermatologue Médecin Esthétique Dermato-chirur...,Tunis,"Rue Apollo XI, Mutuelleville 1002, Tunisie",4.7,24,Dermatologue Médecin Esthétique Dermato-chirur...,NaN
15,214f1cce-d8f0-4e94-8d7e-42ea5f025bd7,Amel,Elloumi Jellouli,Dermatologue,Tunis,"5ème étage Cabinet 1, Clinique Les Jasmins, Ce...",5.0,13,NaN,NaN
16,305ec87f-9a19-4efc-92e7-a83ef2ba79b7,Trojjet,Aouina Sondes,Dermatologue,Tunis,"B3-1, Le cercle des bureaux, Bd de la Terre, T...",5.0,27,NaN,NaN
17,6f326ea1-9ab7-4720-8b44-d2184e146b19,Amel,Amel Mebazaa Najar,Dermatologue,Tunis,"Yasmine Tower, Bd de la Terre, Tunis, Tunisie",4.9,28,NaN,NaN
18,a3ad2d46-41bd-4690-b23f-628dd76e92c0,Imen,Imen Hanchi Ben Zid,Dermatologue,Tunis,"Résidence CHERIFA Bloc B, 2 ème étage Tunis, 2...",4.7,45,NaN,NaN
19,c23d780a-b2bc-447a-ba4f-37a4881ffc00,Meriem,Meriem KACHOUKH,Dermatologue Médecin Esthétique Dermato-chirur...,Tunis,"3ème étage cabinet n°2, cité al khadra, Al kin...",4.7,56,NaN,NaN
20,d85453e6-0d31-4a7f-bbf1-b43d51be6e2d,Mohamed Ali,Gamara,Dermatologue,Tunis,"3 éme étage , B31, Tlili Centre, 46 Av. Habib ...",4.9,173,NaN,NaN
21,2e4c4fa4-5f99-43ca-b7f0-ebda7dd643a0,Slim,Ben Ali Dermatologue,Dermatologue,Tunis,"Tunis, Tunisie",4.7,51,NaN,NaN
22,83d3d93c-f8bf-4650-b43b-de16a13f1b54,Héla,Haouet Marrakchi,Dermatologue,Tunis,"R59R+P74, Tunis, Tunisie",4.7,26,NaN,NaN
23,d70024a1-48c8-4554-9f08-2ce8cd4676a7,Sana,Said Hamila,Dermatologue,Tunis,"Centre médical Tunisie médicale, Av. Hédi Noui...",4.4,68,NaN,NaN
24,8f2dbbbe-c41f-4135-931d-3d06a91ac80a,Sana,Bouchouicha,Dermatologue,Tunis,"Unnamed Road, Tunis, Tunisie",4.2,70,NaN,NaN
25,1fb7d63d-9055-43a6-aa0d-d08fed5acffd,Samira,yahya jouini dermatologue,Dermatologue,Tunis,"Bardo centre bloc 4 cabinet 18, 2000, Tunisie",4.8,46,NaN,NaN
26,23e558de-d749-4f2e-a010-d718619053d0,Skin.tn,Skin.tn,Dermatologue,Tunis,"03 Rue Jaafar El Barmaki, Tunis 1082, Tunisie",4.7,1434,NaN,NaN
27,58438c19-cb43-4edd-8d7e-8e6005161083,Asma,Sioud,Dermatologue,Tunis,"Tunis, Tunisie",4.2,74,NaN,NaN
28,535d5e83-c83b-43cb-a374-bece746c3125,Catherine,Nagati,Dermatologue,Tunis,"Immeuble Touta Saadi, Tour AB, 5ème étage, App...",4.7,15,NaN,NaN
29,68569090-7c86-42c0-9a76-7484866e8738,Ikram,El Amri ep Gribaa,Dermatologue,Sousse,"bloc A 4 ème étage, au-dessus pharmacie kemich...",4.6,89,NaN,NaN

In [48]:
def clean_duplicate_names(df):
    """
    Supprime le prénom du nom de famille quand il est dupliqué
    Exemple: first_name = "Meriem", last_name = "Meriem KACHOUKH" 
             -> devient last_name = "KACHOUKH"
    """
    
    for idx, row in df.iterrows():
        first = str(row['first_name']).strip() if pd.notna(row['first_name']) else ""
        last = str(row['last_name']).strip() if pd.notna(row['last_name']) else ""
        
        # Si le prénom est présent dans le nom de famille
        if first and last and first.lower() in last.lower():
            # Supprimer le prénom du nom de famille
            last_clean = re.sub(re.escape(first), '', last, flags=re.IGNORECASE)
            # Supprimer les espaces multiples et nettoyer
            last_clean = ' '.join(last_clean.split()).strip()
            df.at[idx, 'last_name'] = last_clean
            print(f"✅ Corrigé: {first} {last} -> {first} {last_clean}")
    
    return df

# Utilisation

In [49]:
df_before = df.copy()
df = clean_duplicate_names(df)

✅ Corrigé: Amel Amel Mebazaa Najar -> Amel Mebazaa Najar
✅ Corrigé: Imen Imen Hanchi Ben Zid -> Imen Hanchi Ben Zid
✅ Corrigé: Meriem Meriem KACHOUKH -> Meriem KACHOUKH
✅ Corrigé: Skin.tn Skin.tn -> Skin.tn
✅ Corrigé: Khaoula Khaoula Ben Younes -> Khaoula Ben Younes
✅ Corrigé: Faten Faten Missaoui Ep Belarbi -> Faten Missaoui Ep Belarbi
✅ Corrigé: Olfa Olfa Midassi -> Olfa Midassi
✅ Corrigé: Lobna Lobna Boussofara -> Lobna Boussofara
✅ Corrigé: Farah Farah Abbes -> Farah Abbes
✅ Corrigé: Leila Leila Ariane -> Leila Ariane
✅ Corrigé: Mariem mariem lakhal -> Mariem lakhal
✅ Corrigé: Wafa Wafa Jouini -> Wafa Jouini
✅ Corrigé: Ali DAMAK ALI -> Ali DAMAK
✅ Corrigé: Fatima Fatima Zahra Hamidi Alaoui -> Fatima Zahra Hamidi Alaoui
✅ Corrigé: Nizar Saoudi Nizar -> Nizar Saoudi
✅ Corrigé: Fadhel Ben Romdhane Fadhel -> Fadhel Ben Romdhane
✅ Corrigé: Meriem Meriem Fourati -> Meriem Fourati
✅ Corrigé: Sarrah Ben Meriem Sarrah -> Sarrah Ben Meriem
✅ Corrigé: Miriam Miriam Saad -> Miriam Saad
✅ Corrigé: Sana Sana chouk Friaa -> Sana chouk Friaa
✅ Corrigé: Hela Zribi El Mufti Hela -> Hela Zribi El Mufti
✅ Corrigé: Kamel Kamel Baccouche -> Kamel Baccouche
✅ Corrigé: Mohamed Mohamed Djait -> Mohamed Djait
✅ Corrigé: AMARA AMARA -> AMARA
✅ Corrigé: Wassila Hadrouk Wassila -> Wassila Hadrouk
✅ Corrigé: Mariem docteur Balti Mariem -> Mariem docteur Balti
✅ Corrigé: Chalbi Docteur Chalbi Belkahia -> Chalbi Docteur Belkahia
✅ Corrigé: Donia Docteur Donia Ammar Ben Salem -> Donia Docteur Ammar Ben Salem
✅ Corrigé: Nadia Nadia Ghannouchi -> Nadia Ghannouchi

In [50]:
df.head(50)

,id,first_name,last_name,specialty,city,location,avg_rating,rating_count,description,image
0,0b574b8d-e954-4a77-b97e-ad85b9ab5f30,Jihen,HICHERI,Dermatologue,Ariana,"Centre Médical IRIS, 2037 Av. Hédi Nouira, Ari...",4.3,47,Dermatologie - Maladies Sexuellement Transmiss...,NaN
1,a4716f9d-3d3e-41ca-8aec-a415ff92f2f9,Manel,Karray Zahaf,Dermatologue,Tunis,"Centre El Manar Médical, 2 Rue Tahar Sfar, Tun...",4.9,40,NaN,NaN
2,b8593226-d642-432b-9f02-9cae9c1697b9,Alya,GARGOURI GHARBI,Dermatologue,Tunis,"IBN NAFIS MEDICAL, 84 bis Av. Habib Bourguiba,...",4.2,45,NaN,NaN
3,550e8400-e29b-41d4-a716-446655440000,Wafa,jouini,Dermatologue,Ariana,"1er étage, Apt B1, Centre médical el andalous,...",4.7,55,Le Dr Wafa JOUINI est Dermatologue exerçant à ...,NaN
4,b89b8e98-264d-4bbe-af0a-12bedf2415e4,Jihed,Yacoubi,Dermatologue,Tunis,"Campus Médical, 1 Rue de Tolède, Tunis 2092, T...",5.0,87,NaN,NaN
5,a7f00890-2eaa-461a-ab6b-6f88c512f557,Amel,JELLOULI ELLOUMI,Dermatologue,Tunis,"5ème étage Cabinet 1, Clinique Les Jasmins, Ce...",5.0,13,Spécialiste en Dermatologie - Ancien Médecin P...,NaN
6,9f8fa7f5-e506-4704-9e17-55caeddf88b2,Yosra,JMOUR,Dermatologue,Tunis,"centre médical Lake Tower, Avenue Beji caid Es...",4.1,33,Dermatologie - Maladies de la peau - Maladies ...,NaN
7,9047dd0d-d2e2-4136-ad16-4e94cfb94d5d,Slim,BEN ALI,Dermatologue,Tunis,"Tunis, Tunisie",4.7,51,Diplôme de médecin spécialiste en dermatologie...,NaN
8,91fbabfd-f183-4f06-8e77-94d96411ed9d,Hanen,HAJ TAIEB MEHDI,Dermatologue,Tunis,Soukra Médical Cabinet N°C5 3éme étage، Rue Ch...,4.2,15,Spécialiste en Dermatologie - Maladies Sexuell...,NaN
9,d19839a8-97c2-41a1-a55a-a4408520043e,Zineb,BENNANI,Dermatologue,Tunis,"centre médical sabri, 19, bis Av. de la Républ...",4.0,45,Dermatologie - Maladies des ongles et du cuir ...,NaN
10,4d15d3ef-18c5-473d-a20a-e9e30a44380e,Rim,Cheikh Rouhou Triki,Dermatologue,Tunis,"El Bader Médical, 53 Avenue Moheiddine Klibi, ...",4.8,53,NaN,NaN
11,89b7194b-2d00-4ffe-b83e-b83bf6ccd5e7,Oumayma,Magdoud Dermatologue,Dermatologue,Tunis,"1er étage, app 6, Bloc B, Immeuble Le Palace, ...",4.8,49,NaN,NaN
12,54ef5be6-4146-4250-b9ce-eabb8185604e,Houda,Kennou dermatologue,Dermatologue,Tunis,"44 Av. de La Liberté, Tunis 1002, Tunisie",4.7,38,NaN,NaN
13,8a688677-4a3b-4305-87b0-d3c237809351,Amel,SOUISSI HAJAIEJ,Dermatologue,Tunis,"d'Amérique, 13 bis Av. Des Etats Unis, Tunis 1...",4.6,190,NaN,NaN
14,78186a02-fefa-464c-add9-e19e3341b14e,Leila,Ben Rejeb Ep Riahi,Dermatologue Médecin Esthétique Dermato-chirur...,Tunis,"Rue Apollo XI, Mutuelleville 1002, Tunisie",4.7,24,Dermatologue Médecin Esthétique Dermato-chirur...,NaN
15,214f1cce-d8f0-4e94-8d7e-42ea5f025bd7,Amel,Elloumi Jellouli,Dermatologue,Tunis,"5ème étage Cabinet 1, Clinique Les Jasmins, Ce...",5.0,13,NaN,NaN
16,305ec87f-9a19-4efc-92e7-a83ef2ba79b7,Trojjet,Aouina Sondes,Dermatologue,Tunis,"B3-1, Le cercle des bureaux, Bd de la Terre, T...",5.0,27,NaN,NaN
17,6f326ea1-9ab7-4720-8b44-d2184e146b19,Amel,Mebazaa Najar,Dermatologue,Tunis,"Yasmine Tower, Bd de la Terre, Tunis, Tunisie",4.9,28,NaN,NaN
18,a3ad2d46-41bd-4690-b23f-628dd76e92c0,Imen,Hanchi Ben Zid,Dermatologue,Tunis,"Résidence CHERIFA Bloc B, 2 ème étage Tunis, 2...",4.7,45,NaN,NaN
19,c23d780a-b2bc-447a-ba4f-37a4881ffc00,Meriem,KACHOUKH,Dermatologue Médecin Esthétique Dermato-chirur...,Tunis,"3ème étage cabinet n°2, cité al khadra, Al kin...",4.7,56,NaN,NaN
20,d85453e6-0d31-4a7f-bbf1-b43d51be6e2d,Mohamed Ali,Gamara,Dermatologue,Tunis,"3 éme étage , B31, Tlili Centre, 46 Av. Habib ...",4.9,173,NaN,NaN
21,2e4c4fa4-5f99-43ca-b7f0-ebda7dd643a0,Slim,Ben Ali Dermatologue,Dermatologue,Tunis,"Tunis, Tunisie",4.7,51,NaN,NaN
22,83d3d93c-f8bf-4650-b43b-de16a13f1b54,Héla,Haouet Marrakchi,Dermatologue,Tunis,"R59R+P74, Tunis, Tunisie",4.7,26,NaN,NaN
23,d70024a1-48c8-4554-9f08-2ce8cd4676a7,Sana,Said Hamila,Dermatologue,Tunis,"Centre médical Tunisie médicale, Av. Hédi Noui...",4.4,68,NaN,NaN
24,8f2dbbbe-c41f-4135-931d-3d06a91ac80a,Sana,Bouchouicha,Dermatologue,Tunis,"Unnamed Road, Tunis, Tunisie",4.2,70,NaN,NaN
25,1fb7d63d-9055-43a6-aa0d-d08fed5acffd,Samira,yahya jouini dermatologue,Dermatologue,Tunis,"Bardo centre bloc 4 cabinet 18, 2000, Tunisie",4.8,46,NaN,NaN
26,23e558de-d749-4f2e-a010-d718619053d0,Skin.tn,,Dermatologue,Tunis,"03 Rue Jaafar El Barmaki, Tunis 1082, Tunisie",4.7,1434,NaN,NaN
27,58438c19-cb43-4edd-8d7e-8e6005161083,Asma,Sioud,Dermatologue,Tunis,"Tunis, Tunisie",4.2,74,NaN,NaN
28,535d5e83-c83b-43cb-a374-bece746c3125,Catherine,Nagati,Dermatologue,Tunis,"Immeuble Touta Saadi, Tour AB, 5ème étage, App...",4.7,15,NaN,NaN
29,68569090-7c86-42c0-9a76-7484866e8738,Ikram,El Amri ep Gribaa,Dermatologue,Sousse,"bloc A 4 ème étage, au-dessus pharmacie kemich...",4.6,89,NaN,NaN
30,52864772-8618-429a-9bb2-eac364b2c772,Aycha,AROUSSE,Dermatologue,Sousse,"ZAOUI MEDICAL TROCADERO, Av. de la Republique,...",4.8,60,NaN,NaN
31,c695c60e-9699-4b77-9e3d-24c5da7feccd,TOUMI,AYMEN DERMATOLOGUE,Dermatologue,Sousse,"VJ24+6QM, Hammam Sousse, Tunisie",4.3,68,NaN,NaN
32,58c00921-070c-4a08-9a86-fdece7f1d9c2,Wafa,Saidi Kacem,Dermatologue,Sousse,"Bloc A 3ème étage, Clinique les Oliviers, N°30...",5.0,6,NaN,NaN
33,1dee5725-8257-4cf8-9cc5-c1737f73e7d5,Colandane,Noueiri Belajouza,Dermatologue,Sousse,"4ème étage cabinet 401, Bloc B, Centre médical...",4.2,10,NaN,NaN
34,8ee360b2-00f8-4bcb-bb03-e923cfb38ab5,zeineb,ben said khalfallah,Dermatologue,Sousse,"Kantaoui médical center, Hammam Sousse 4011, T...",5.0,4,NaN,NaN
35,6d22ebf2-09cc-49d5-ad96-3a8d46d52210,Amira,Zaouali Ep Miled,Dermatologue,Sousse,"Panoramعمارة الوفاقa Médical, Avenue Taieb Mhi...",4.0,4,NaN,NaN
36,b1501bce-9033-45cb-910c-767f9f5cc2b1,Bouraoui,Badday,Dermatologue,Sousse,"RJJR+F49, Sousse 4000, Tunisie",5.0,3,NaN,NaN
37,81793cb8-70b4-4ecb-a0d4-9826478eb268,Ashraf,laroussi mellouli,Dermatologue,Sousse,"bloc c 1er étage, Clinique les oliviers, Av. 1...",5.0,6,NaN,NaN
38,c202a760-2d88-4a11-8938-d84574c9472b,Jihen,BELHOUANE REJEB,Dermatologue,Sousse,"En face de l'hôpital de Sahloul, Immeuble Lotu...",4.9,9,NaN,NaN
39,c82510ea-897a-467b-80f9-b5ba4b691714,Mohamed,DENGUEZLI,Dermatologue,Sousse,"RJGJ+RPJ Hached, Sousse, Sousse, Tunisie",0.0,0,NaN,NaN
40,5111ec41-2e69-4592-bac2-7c36b6ba9a02,Bouraouia,MAKHLOUF BNOUNI,Dermatologue,Sousse,"RJJP+68F, Av. de la Republique, Sousse, Tunisie",5.0,4,NaN,NaN
41,97e9cb89-d727-471f-b228-85126fffe166,Faten,CHEBIL,Dermatologue,Sousse,"appartement N° 206 2ème étage, Immeuble Avicen...",5.0,10,NaN,NaN
42,8b8d2b60-fb17-411b-8990-6a79ecd2673a,nesrine,kenani kassassi,Dermatologue,Sousse,"Khezama est, clinique les oliviers bloc c 1ère...",4.4,10,NaN,NaN
43,7530fda2-5c72-4013-9d19-bd88cd0cee9b,SAMI,GUETAT,Dermatologue,Tunis,Le Carrefour Médical - 2 éme étage - Cabinet 2...,4.1,168,NaN,NaN
44,142be124-1381-4cf4-80a0-0e01392af88d,Randa,DR Yaakoubi,Dermatologue,Sousse,"Résidence el Ahmed, Av. de Yasser Arafat, Sous...",5.0,28,NaN,NaN
45,4a431b37-aa85-4d60-8994-0cb688bb2fe2,Khaoula,Ben Younes,Dermatologue,Sfax,"Immeuble la couronne, Av. Hédi Nouira, Sfax 30...",4.8,66,NaN,NaN
46,4c7c124c-7754-4923-9d06-2d90313b324b,Mariem,JRIBI Ben Henia,Dermatologue & Médecin Esthétique,Sousse,"Place du Grand Maghreb, Résidence Médicale Ess...",4.4,48,NaN,NaN
47,51df0a85-2160-4fb1-95c0-81a2c38050a2,Lilia,Ben M’Barek Hamida,Dermatologue,Tunis,"R5JG+8FF, Rue Abou Hanifa, Tunis, Tunisie",4.9,13,NaN,NaN
48,54495899-983a-425b-8e30-d9680e64eae6,Faten,Missaoui Ep Belarbi,Dermatologue,Sousse,"Cite Riyadh, Rue Abdelaziz Rjiba، Sousse 4023,...",4.9,58,NaN,NaN
49,87930663-1889-459e-917c-95549358bbcd,samah,ben dhia,Dermatologue,Sousse,"3ème étage, Avenue habib bourguiba bab bhar ce...",5.0,1,NaN,NaN

In [54]:
def clean_doctor_titles(df):
    """
    Supprime les titres (Dr, Docteur, Dermatologue, Cabinet, etc.) 
    des colonnes first_name et last_name
    """
    
    # Liste des titres à supprimer
    titles = [
        'dr', 'dr.', 'docteur', 'dermatologue', 'dermato', 
        'cabinet', 'clinic', 'clinique', 'medecin', 'médecin',
        'doct', 'pr', 'prof', 'professeur', 'specialist',
        'centre', 'office', 'clinicien'
    ]
    
    for idx, row in df.iterrows():
        
        # Nettoyer first_name
        first = str(row['first_name']) if pd.notna(row['first_name']) else ""
        if first:
            first_lower = first.lower()
            for title in titles:
                if first_lower.startswith(title):
                    first = re.sub(rf'^{title}\.?', '', first, flags=re.IGNORECASE).strip()
                    break
            df.at[idx, 'first_name'] = first.title() if first else ""
        
        # Nettoyer last_name
        last = str(row['last_name']) if pd.notna(row['last_name']) else ""
        if last:
            last_lower = last.lower()
            for title in titles:
                if last_lower.startswith(title):
                    last = re.sub(rf'^{title}\.?', '', last, flags=re.IGNORECASE).strip()
                    break
            # Supprimer aussi "dermatologue" n'importe où
            last = re.sub(r'dermatologue', '', last, flags=re.IGNORECASE).strip()
            df.at[idx, 'last_name'] = last.title() if last else ""
    
    return df

In [55]:
# Exécuter la fonction
df = clean_doctor_titles(df)

In [56]:
df.head(20)

,id,first_name,last_name,specialty,city,location,avg_rating,rating_count,description,image
0,0b574b8d-e954-4a77-b97e-ad85b9ab5f30,Jihen,Hicheri,Dermatologue,Ariana,"Centre Médical IRIS, 2037 Av. Hédi Nouira, Ari...",4.3,47,Dermatologie - Maladies Sexuellement Transmiss...,NaN
1,a4716f9d-3d3e-41ca-8aec-a415ff92f2f9,Manel,Karray Zahaf,Dermatologue,Tunis,"Centre El Manar Médical, 2 Rue Tahar Sfar, Tun...",4.9,40,NaN,NaN
2,b8593226-d642-432b-9f02-9cae9c1697b9,Alya,Gargouri Gharbi,Dermatologue,Tunis,"IBN NAFIS MEDICAL, 84 bis Av. Habib Bourguiba,...",4.2,45,NaN,NaN
3,550e8400-e29b-41d4-a716-446655440000,Wafa,Jouini,Dermatologue,Ariana,"1er étage, Apt B1, Centre médical el andalous,...",4.7,55,Le Dr Wafa JOUINI est Dermatologue exerçant à ...,NaN
4,b89b8e98-264d-4bbe-af0a-12bedf2415e4,Jihed,Yacoubi,Dermatologue,Tunis,"Campus Médical, 1 Rue de Tolède, Tunis 2092, T...",5.0,87,NaN,NaN
5,a7f00890-2eaa-461a-ab6b-6f88c512f557,Amel,Jellouli Elloumi,Dermatologue,Tunis,"5ème étage Cabinet 1, Clinique Les Jasmins, Ce...",5.0,13,Spécialiste en Dermatologie - Ancien Médecin P...,NaN
6,9f8fa7f5-e506-4704-9e17-55caeddf88b2,Yosra,Jmour,Dermatologue,Tunis,"centre médical Lake Tower, Avenue Beji caid Es...",4.1,33,Dermatologie - Maladies de la peau - Maladies ...,NaN
7,9047dd0d-d2e2-4136-ad16-4e94cfb94d5d,Slim,Ben Ali,Dermatologue,Tunis,"Tunis, Tunisie",4.7,51,Diplôme de médecin spécialiste en dermatologie...,NaN
8,91fbabfd-f183-4f06-8e77-94d96411ed9d,Hanen,Haj Taieb Mehdi,Dermatologue,Tunis,Soukra Médical Cabinet N°C5 3éme étage، Rue Ch...,4.2,15,Spécialiste en Dermatologie - Maladies Sexuell...,NaN
9,d19839a8-97c2-41a1-a55a-a4408520043e,Zineb,Bennani,Dermatologue,Tunis,"centre médical sabri, 19, bis Av. de la Républ...",4.0,45,Dermatologie - Maladies des ongles et du cuir ...,NaN
10,4d15d3ef-18c5-473d-a20a-e9e30a44380e,Rim,Cheikh Rouhou Triki,Dermatologue,Tunis,"El Bader Médical, 53 Avenue Moheiddine Klibi, ...",4.8,53,NaN,NaN
11,89b7194b-2d00-4ffe-b83e-b83bf6ccd5e7,Oumayma,Magdoud,Dermatologue,Tunis,"1er étage, app 6, Bloc B, Immeuble Le Palace, ...",4.8,49,NaN,NaN
12,54ef5be6-4146-4250-b9ce-eabb8185604e,Houda,Kennou,Dermatologue,Tunis,"44 Av. de La Liberté, Tunis 1002, Tunisie",4.7,38,NaN,NaN
13,8a688677-4a3b-4305-87b0-d3c237809351,Amel,Souissi Hajaiej,Dermatologue,Tunis,"d'Amérique, 13 bis Av. Des Etats Unis, Tunis 1...",4.6,190,NaN,NaN
14,78186a02-fefa-464c-add9-e19e3341b14e,Leila,Ben Rejeb Ep Riahi,Dermatologue Médecin Esthétique Dermato-chirur...,Tunis,"Rue Apollo XI, Mutuelleville 1002, Tunisie",4.7,24,Dermatologue Médecin Esthétique Dermato-chirur...,NaN
15,214f1cce-d8f0-4e94-8d7e-42ea5f025bd7,Amel,Elloumi Jellouli,Dermatologue,Tunis,"5ème étage Cabinet 1, Clinique Les Jasmins, Ce...",5.0,13,NaN,NaN
16,305ec87f-9a19-4efc-92e7-a83ef2ba79b7,Trojjet,Aouina Sondes,Dermatologue,Tunis,"B3-1, Le cercle des bureaux, Bd de la Terre, T...",5.0,27,NaN,NaN
17,6f326ea1-9ab7-4720-8b44-d2184e146b19,Amel,Mebazaa Najar,Dermatologue,Tunis,"Yasmine Tower, Bd de la Terre, Tunis, Tunisie",4.9,28,NaN,NaN
18,a3ad2d46-41bd-4690-b23f-628dd76e92c0,Imen,Hanchi Ben Zid,Dermatologue,Tunis,"Résidence CHERIFA Bloc B, 2 ème étage Tunis, 2...",4.7,45,NaN,NaN
19,c23d780a-b2bc-447a-ba4f-37a4881ffc00,Meriem,Kachoukh,Dermatologue Médecin Esthétique Dermato-chirur...,Tunis,"3ème étage cabinet n°2, cité al khadra, Al kin...",4.7,56,NaN,NaN

In [57]:
def recommend_weighted_score(df, city=None, top_n=10):
    """
    Recommande avec un score pondéré:
    - Note: 70%
    - Popularité (nombre d'avis): 30%
    """
    
    filtered_df = df.copy()
    
    #if city:
    #    filtered_df = filtered_df[filtered_df['city'].str.lower() == city.lower()]
    
    filtered_df = filtered_df[filtered_df['avg_rating'] > 0]
    
    # Normaliser les notes (0-1)
    max_rating = filtered_df['avg_rating'].max()
    filtered_df['rating_norm'] = filtered_df['avg_rating'] / max_rating
    
    # Normaliser le nombre d'avis (0-1)
    max_reviews = filtered_df['rating_count'].max()
    filtered_df['reviews_norm'] = filtered_df['rating_count'] / max_reviews if max_reviews > 0 else 0
    
    # Score pondéré: 70% note + 30% popularité
    filtered_df['weighted_score'] = (filtered_df['rating_norm'] * 0.7) + (filtered_df['reviews_norm'] * 0.3)
    
    recommendations = filtered_df.sort_values('weighted_score', ascending=False).head(top_n)
    
    return recommendations[['first_name', 'last_name', 'city', 'avg_rating', 'rating_count', 'weighted_score']]

print("\n🏆 TOP 10 (Score pondéré):")
print(recommend_weighted_score(df, top_n=10))

🏆 TOP 10 (Score pondéré):
      first_name  last_name      city  avg_rating  rating_count  \
26       Skin.Tn                Tunis         4.7          1434
119         Wafa      Jribi  La Marsa         5.0           181
20   Mohamed Ali     Gamara     Tunis         4.9           173
144     Marzouk      Nabeul    Nabeul         5.0           102
4         Jihed     Yacoubi     Tunis         5.0            87
147      Wassila    Hadrouk    Nabeul         5.0            55
54         Lynda  Said Riba    Sousse         5.0            48
107        Nizar     Saoudi  La Marsa         5.0            35
98       Jaouadi      Manel  La Marsa         4.9            98
44         Randa   Yaakoubi    Sousse         5.0            28

     weighted_score
26         0.958000
119        0.737866
20         0.722192
144        0.721339
4          0.718201
147        0.711506
54         0.710042
107        0.707322
98         0.706502
44         0.705858

In [58]:
# Sauvegarder le DataFrame nettoyé en CSV
df.to_csv("data/doctors_cleaned.csv", index=False, encoding='utf-8')

print("✅ Dataset nettoyé sauvegardé !")
print(f"📁 Emplacement: data/doctors_cleaned.csv")
print(f"📊 Nombre de lignes: {len(df)}")
print(f"📋 Colonnes: {list(df.columns)}")

✅ Dataset nettoyé sauvegardé !
📁 Emplacement: data/doctors_cleaned.csv
📊 Nombre de lignes: 155
📋 Colonnes: ['id', 'first_name', 'last_name', 'specialty', 'city', 'location', 'avg_rating', 'rating_count', 'description', 'image']